
spring:
  application:
    name: 'Demo'

  datasource:
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create